name: CI
on:
  push:
    branches:
      - backup 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" | tr -d '\r' > ~/.ssh/id_rsa
          echo "$HEXO_DEPLOY_PRI"
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "tedmax100"
          git config --global user.email "tedmax100@gmail.com"
      - name: Update themes
        run: |
          git submodule init
          git submodule update
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      - name: Generate hexo
        run: |
          hexo generate
      - name: Deploy hexo
        run: |
          hexo deploy